Changed the Readme a bit
MakeContributions/.github pull request #1
Opened 2022-07-23 11:14 UTC by AvidCoder101

@ming-tsai Wanted to contribute, and noticed that the README was a little empty, so I just added a little more info. Please tell me if I need to change anything or if I have any errors. Thanks (:

2022-07-23 18:49 UTC, ming-tsai requested changes
Hi @AvidCoder101,
Could you check how to made the markdown more beautiful?

2022-07-23 20:59 UTC, AvidCoder101 commented
Of course, could you give some suggestions on what to do, like if you'd like a banner?

2022-07-24 14:05 UTC, ming-tsai commented
> Of course, could you give some suggestions on what to do, like if you'd like a banner?

Ok, I will give a suggestion

2022-07-26 15:25 UTC, ming-tsai commented
> Of course, could you give some suggestions on what to do, like if you'd like a banner?

Hi @AvidCoder101,
This is my recommendation.

**Code**
```md
## Hi there 👋, we are Make Contributions
<!--

**Here are some ideas to get you started:**

🙋‍♀️ A short introduction - what is your organization all about?
🌈 Contribution guidelines - how can the community get involved?
👩‍💻 Useful resources - where can the community find your docs? Is there anything else the community should know?
🍿 Fun facts - what does your team eat for breakfast?
🧙 Remember, you can do mighty things with the power of [Markdown](https://guides.github.com/features/mastering-markdown/)
-->

We are an organization that wants to encourage Github newbies to come and participate in open source projects and contribute more to Github (well, the clue in the name 😉).

### There's plenty to take part in the organizing, check out some of our repositories below:

- [DSA](https://github.com/MakeContributions/DSA) - Data Structure and Algorithm (DSA) contributions
- [markdown-dungeon](https://github.com/MakeContributions/markdown-dungeon) - A dungeon made fully out of markdown.
- [ideahub](https://github.com/MakeContributions/ideahub) - A collection of ideas and projects that contain from beginner to advance :octocat: 🎯🚀

> One of our maintainers can add you to the organization once you contribute if you'd like to join, and you could be part of the growing community of over 200 members. Do you want to contact us? Email tsaibot@outlook.com
```

**Rendered**
## Hi there 👋, we are Make Contributions
<!--

**Here are some ideas to get you started:**

🙋‍♀️ A short introduction - what is your organization all about?
🌈 Contribution guidelines - how can the community get involved?
👩‍💻 Useful resources - where can the community find your docs? Is there anything else the community should know?
🍿 Fun facts - what does your team eat for breakfast?
🧙 Remember, you can do mighty things with the power of [Markdown](https://guides.github.com/features/mastering-markdown/)
-->

We are an organization that wants to encourage Github newbies to come and participate in open source projects and contribute more to Github (well, the clue in the name 😉).

### There's plenty to take part in the organizing, check out some of our repositories below:

- [DSA](https://github.com/MakeContributions/DSA) - Data Structure and Algorithm (DSA) contributions
- [markdown-dungeon](https://github.com/MakeContributions/markdown-dungeon) - A dungeon made fully out of markdown.
- [ideahub](https://github.com/MakeContributions/ideahub) - A collection of ideas and projects that contain from beginner to advance :octocat: 🎯🚀

> One of our maintainers can add you to the organization once you contribute if you'd like to join, and you could be part of the growing community of over 200 members. Do you want to contact us? Email tsaibot@outlook.com

2022-07-26 15:36 UTC, AvidCoder101 commented
Thanks, I will add this is and anything else I think is relevant :)

2022-07-26 15:47 UTC, AvidCoder101 commented
@ming-tsai I changed it

2022-07-26 16:00 UTC, ming-tsai commented on profile/README.md
> +
```suggestion
## Hi there 👋, we are Make Contributions
<!--

**Here are some ideas to get you started:**

🙋‍♀️ A short introduction - what is your organization all about?
🌈 Contribution guidelines - how can the community get involved?
👩‍💻 Useful resources - where can the community find your docs? Is there anything else the community should know?
🍿 Fun facts - what does your team eat for breakfast?
🧙 Remember, you can do mighty things with the power of [Markdown](https://guides.github.com/features/mastering-markdown/)
-->

We are an organization that wants to encourage Github newbies to come and participate in open source projects and contribute more to Github (well, the clue in the name 😉).

### There's plenty to take part in the organizing, check out some of our repositories below:

- [DSA](https://github.com/MakeContributions/DSA) - Data Structure and Algorithm (DSA) contributions
- [markdown-dungeon](https://github.com/MakeContributions/markdown-dungeon) - A dungeon made fully out of markdown.
- [ideahub](https://github.com/MakeContributions/ideahub) - A collection of ideas and projects that contain from beginner to advance :octocat: 🎯🚀

> One of our maintainers can add you to the organization once you contribute if you'd like to join, and you could be part of the growing community of over 200 members. Do you want to contact us? Email tsaibot@outlook.com

```

2022-07-26 16:00 UTC, ming-tsai approved these changes

2022-07-26 16:01 UTC, merged